[build]
  publish = "."

[[headers]]
  for = "/tools.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Content-Type = "application/json; charset=utf-8"
